# Generated by Django 4.0.2 on 2022-03-12 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_logo', models.ImageField(upload_to='images')),
                ('Company_name', models.CharField(max_length=100)),
                ('Services', models.CharField(max_length=200)),
                ('Company_start_date', models.DateField(null=True)),
                ('Websites', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='candiate_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_photo', models.ImageField(upload_to='images')),
                ('Candidate_name', models.CharField(max_length=100)),
                ('Cv', models.FileField(upload_to='')),
                ('Skills', models.CharField(max_length=200)),
                ('Experience', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candiate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
