# Generated by Django 4.0.2 on 2022-03-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_company_profile_candiate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candiate_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candiate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
