# Generated by Django 4.0.2 on 2022-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candiate_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_details', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Experience', models.PositiveIntegerField(default=1)),
                ('Salary', models.PositiveIntegerField(default=15000)),
            ],
        ),
        migrations.DeleteModel(
            name='candiate_profile',
        ),
    ]
