# Generated by Django 4.0.2 on 2022-03-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candiate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candiate_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candiate', to=settings.AUTH_USER_MODEL),
        ),
    ]
