# Generated by Django 4.0.2 on 2022-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candiateprofile_user_jobs_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candiateprofile',
            name='Cv',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Company_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='candidate.company_profile'),
        ),
    ]
