# Generated by Django 4.0.2 on 2022-03-16 20:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_candidateprofile_delete_candiateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.PositiveIntegerField(max_length=10)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('grad_year', models.IntegerField(blank=True)),
                ('postion_for_which_you_applying', models.CharField(max_length=100)),
                ('Prefer_working_mode', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=100, null=True)),
                ('resume', models.FileField(null=True, upload_to='resumes')),
            ],
        ),
    ]
