# Generated by Django 4.0.2 on 2022-03-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_applicationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='Application',
        ),
    ]
