# Generated by Django 4.0.2 on 2022-03-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_rename_applicationform_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='candidate.company_profile'),
        ),
    ]
