# Generated by Django 4.0.2 on 2022-03-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_alter_application_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.company_profile'),
        ),
    ]
