# Generated by Django 4.0.2 on 2022-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='male', max_length=200, null=True),
        ),
    ]
