# Generated by Django 4.0.2 on 2022-03-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_remove_application_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
