# Generated by Django 4.0.2 on 2022-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_my_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_application',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('Intransit', 'Intransit'), ('delivered', 'delivered'), ('Dispatched', 'Dispatched'), ('order_placed', 'order_placed')], default='order_placed', max_length=120),
        ),
    ]
