# Generated by Django 4.0.2 on 2022-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_alter_my_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Prefer_working_mode',
        ),
        migrations.AlterField(
            model_name='my_application',
            name='status',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('delivered', 'delivered'), ('cancel', 'cancel'), ('Dispatched', 'Dispatched'), ('Intransit', 'Intransit')], default='order_placed', max_length=120),
        ),
    ]
